#!/bin/bash

cd lede

git clone https://github.com/rufengsuixing/luci-app-adguardhome package/myapp/luci-app-adguardhome
git clone https://github.com/2512500960/zzu-minieap-openwrt package/myapp/zzu-minieap-openwrt
git clone https://github.com/tty228/luci-app-serverchan package/myapp/luci-app-serverchan
git clone https://github.com/project-lede/luci-app-godproxy package/myapp/luci-app-godproxy
git clone https://github.com/tuanqing/install-program package/myapp/install-program
# helloworld
sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
# add Lienol's package
sed -i '$a src-git lienol https://github.com/Lienol/openwrt-package' feeds.conf.default
# replace antfs 
sed -i 's/antfs-mount/ntfs-3g/g' ./package/lean/automount/Makefile
./scripts/feeds update -a
./scripts/feeds install -a
sed -i '34 s/$/ +libselinux +libsepol/' feeds/packages/utils/lvm2/Makefile
sed -i '34 s/$/ +libselinux/' feeds/packages/utils/vim/Makefile
sed -i '/FEATURES+=/ { s/cpiogz //; s/ext4 //; s/ramdisk //; s/squashfs //; }' target/linux/armvirt/Makefile

sed -i '$d' target/linux/armvirt/image/Makefile
echo -e 'define Device/Phicomm-n1
DEVICE_MODEL := Phicomm-n1
  DEVICE_PACKAGES := \
    brcmfmac-firmware-43430-sdio \
    brcmfmac-firmware-43430-sdio-rpi-3b \
    brcmfmac-firmware-43455-sdio \
    brcmfmac-firmware-43455-sdio-rpi-3b-plus \
    kmod-brcmfmac wpad \
    bash vim \
    kmod-fs-ext4 kmod-fs-vfat kmod-fs-exfat dosfstools e2fsprogs ntfs-3g \
    kmod-usb-storage kmod-usb-storage-extras kmod-usb-storage-uas \
    kmod-usb-net kmod-usb-net-asix-ax88179 kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 \
    blkid lsblk parted fdisk cfdisk losetup resize2fs tune2fs pv unzip \
    lscpu htop iperf3 curl lm-sensors install-program 
endef
ifeq ($(SUBTARGET),64)
  TARGET_DEVICES += Phicomm-n1
endif\n
$(eval $(call BuildImage))' >> ./target/linux/armvirt/image/Makefile

cp ../.github/n1.config .config 
make defconfig

